version: "3.9"

services:
  main:
    build: .
    ports:
      - 5900:5900
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/astrodmx/.Xauthority
      - ./data:/home/astrodmx/AstroDMx_DATA
      - ./settings:/home/astrodmx/.AstroDMx
    environment:
      - DISPLAY=$DISPLAY
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    privileged: true
    restart: unless-stopped
